GET {{ API_URL }}:{{ API_PORT }}/api/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IndvamNpZWNoLmd1emUxMjMiLCJpYXQiOjE2OTM5MjE2NzQsImV4cCI6MTY5MzkyODg3NH0.daTZ85kPxoXQMPp2WaRbCF-wUiMsFS6BDegwiOh8cjo