GET {{ API_URL }}:{{ API_PORT }}/api/user/token/test
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJ1c2VybmFtZSI6InRlc3QtdXNlciIsImlhdCI6MTY5Mzg2NjQwNCwiZXhwIjoxNjkzODczNjA0fQ.Dq6BTww05hpuUX2bNfJhVrKMfNMxjgFmcGUjr3j0snw