const JWT_AUTHENTICATION_TOKEN_EXPIRES = '2h'
const USER_PASSWORD_BCRYPT_SALT = 10
const USER_REGISTER_BONUS_CODE = 'register-bonus'

module.exports = {
    JWT_AUTHENTICATION_TOKEN_EXPIRES,
    USER_PASSWORD_BCRYPT_SALT,
    USER_REGISTER_BONUS_CODE
}