POST {{ API_URL }}:{{ API_PORT }}/api/games
Content-Type: application/json

{
  "gameName": "Test game",
  "gameCostBaseValue": 20,
  "gameValues": [
    {
      "value": "Value 1",
      "chance": 20,
      "currencyId": 1
    },
    {
      "value": "Value 2",
      "chance": 30,
      "currencyId": 1
    },
    {
      "value": "Value 3",
      "chance": 30,
      "currencyId": 1
    },
    {
      "value": "Value 4",
      "chance": 10,
      "currencyId": 1
    },
    {
      "value": "Value 5",
      "chance": 10,
      "currencyId": 1
    }
  ]
}