POST {{ API_URL }}:{{ API_PORT }}/api/games
Content-Type: application/json

{
  "gameName": "Test game",
  "gameCostBaseValue": 20,
  "gameValues": [
    {
      "value": 10,
      "chance": 20,
      "currencyId": 1
    },
    {
      "value": 20,
      "chance": 30,
      "currencyId": 1
    },
    {
      "value": 30,
      "chance": 30,
      "currencyId": 1
    },
    {
      "value": 40,
      "chance": 10,
      "currencyId": 1
    },
    {
      "value": 50,
      "chance": 10,
      "currencyId": 1
    }
  ]
}