PATCH {{API_URL}}:{{API_PORT}}/api/games
Content-Type: application/json

{
  "gameId": 2,
  "gameName": "Test game (updated)",
  "gameCostBaseValue": 20,
  "gameValues": [
    {
      "value": "New value 1",
      "chance": 60,
      "currencyId": 1
    },
    {
      "value": "New value 2",
      "chance": 40,
      "currencyId": 1
    }
  ]
}